document.addEventListener("DOMContentLoaded", () => {
	const facts = [
		"Did you know bananas are berries, but strawberries aren't?",
		"Did you know octopuses have three hearts?",
		"Did you know your brain uses about the same amount of power as a light bulb?",
		"Did you know the dot over the lowercase 'i' is called a tittle?",
		"Did you know the unicorn is the national animal of Scotland?",
		"You've never seen your own face. Only reflections and photos. Suspicious.",
		"Bees can recognize human faces. So be nice.",
		"Some turtles can breathe through their butts. Not ideal, but effective.",
		"Did you know there's a basketball court on the top floor of the U.S. Supreme Court building?",
		"If a potato wore pants, how would it wear them?",
		"A group of flamingos is called a flamboyance. That’s fabulous.",
		"Did you know cats can't taste sweetness?",
		"Don't trust stairs. They're always up to something.",
		"The word 'boredom' didn’t exist until the 1800s. People had no time to be bored before then.",
		"A snail can sleep for three years. Jealous?",
		"Did you know wombat poop is cube-shaped?",
		"There's a species of fungus that glows in the dark. Because why not?",
		"Some frogs can be frozen solid and still survive. Frogs: 1, Freezers: 0.",
		"Cows have best friends and get stressed when separated. Moo-ving, isn’t it?",
		"Did you know lobsters taste with their legs?",
		"Every time you clean something, you make something else dirty.",
		"Your tongue knows exactly how to find a popcorn kernel stuck in your teeth. It’s got skills.",
		"Did you know sea otters hold hands while sleeping so they don’t drift apart?",
		"You just blinked. Think about that.",
		"Humans share about 60% of their DNA with bananas. Insert fruit joke here.",
		"There’s a town in Norway where it rains fish. Fish forecast: flounder with a chance of mackerel.",
		"The word ‘swims’ looks the same upside down. Weird pool party trick.",
		"Did you know a jiffy is an actual unit of time? It’s 1/100th of a second.",
		"Everything you’ve ever smelled is particles entering your nose. Ew?",
		"Ants can survive in a microwave. Resilient snacks, not recommended.",
		"Sometimes your dog looks at you and just thinks 'meh'.",
		"Your fingers prune in water to improve grip. Evolution made you better at holding soap.",
		"Did you know the inventor of Pringles is buried in a Pringles can? Respect.",
		"Rabbits can't puke. That’s why they always look smug.",
		"The reason you can't tickle yourself is because your brain says 'I know what you’re up to.'",
		"There’s a species of spider named after David Bowie. It's fabulous.",
		"Pigeons can recognize themselves in mirrors. More self-aware than most toddlers.",
		"Did you know honey never spoils? You could be eating ancient bee juice.",
		"The number of ducks it would take to overpower a horse is nonzero. Think about it.",
		"If you think about it, popcorn is just aggressive cereal.",
		"All swans in England technically belong to the Queen. Even Steve. He’s the worst.",
		"If you scream into a jar for 8 years you’ll have enough energy to heat a cup of coffee. Not worth it.",
		"Your skeleton is always wet. Chew on that.",
		"There's no reason sandwiches should be rectangular. We've just accepted that.",
		"A group of porcupines is called a prickle. Aw.",
		"Did you know a shrimp’s heart is in its head?",
		"Tiny shrimp are the reason flamingos are pink. Flamingos are basically walking shrimp ads.",
		"Nobody has ever been in an empty room. Let that sit.",
		"Did you know you can hear rhubarb grow under the right conditions? Plant ASMR.",
		"The phrase 'kick the bucket' might come from cow milking. Which is dark and weird.",
		"The chicken came before the egg. Science says so.",
		"The last thing you touch is always the current thing you’re touching. Mind = blown.",
		"There are more fake flamingos in the world than real ones. Plastic reigns.",
		"If you ever feel useless, just remember glitter has a half-life.",
		"Someone had to invent duct tape. That person was a hero.",
		"Did you know sloths can hold their breath longer than dolphins?",
		"Mount Everest can grow taller due to shifting tectonic plates. Mountains are still growing up.",
		"The average cloud weighs more than 1 million pounds. Heavy mood.",
		"If a tomato is a fruit, ketchup is technically a smoothie.",
		"You can't hum while holding your nose. Still trying? Me too.",
		"The first oranges weren’t orange. Citrus identity crisis.",
		"A day on Venus is longer than a year on Venus. Venus has no chill.",
		"Sharks existed before trees. They are the original bad boys.",
		"Did you know some metals can explode in water? Don’t try this at home.",
		"Your stomach gets a new lining every few days. Self-healing organs are cool.",
		"Elephants think humans are cute. We’re basically their pets.",
		"There’s a town in the U.S. called ‘Nothing’. It’s exactly what it sounds like.",
		"Hot water freezes faster than cold water. Science refuses to explain why properly.",
		"Your feet contain a quarter of all the bones in your body. Weird, huh?",
		"Did you know blue whales are louder than jet engines?",
		"If two vegans get into an argument, is it still called a beef?",
		"“Silent” and “listen” are anagrams. Coincidence? Probably.",
		"Sloths can take up to a month to digest a single leaf. Respect the chill.",
		"The dot on a question mark is called a 'tittle'. Teehee.",
		"Rain smells good because of a compound called petrichor. Or magic.",
		"There's a sport in Finland called 'Wife Carrying'. Not kidding.",
		"Some cows have best friends and get sad when separated. Moo feels.",
		"A single spaghetti noodle is technically called a ‘spaghetto’.",
		"Your nose can remember 50,000 different scents. But still forgets where you put your phone.",
		"A crocodile can't stick its tongue out. Lame party trick.",
		"Did you know there's a planet made of diamonds?",
		"Vending machines are more deadly than sharks. Don’t get snacks alone.",
		"There's a bird that mimics chainsaws. The wild is wild.",
		"If Earth were the size of a marble, the moon would still be pretty far.",
		"If you lick your elbow, congratulations. You’re a rare human being.",
		"If you're reading this, you're alive. And reading. Double win.",
		"Space smells like seared steak, apparently. Space chefs take note.",
		"Humans glow faintly in the dark. But it's too dim to see. We are boring light bulbs.",
		"If you say 'beer can' in a British accent, it sounds like 'bacon' in a Jamaican one.",
		"No one has ever been in a truly silent room. Even silence has background noise.",
		"Your liver can regenerate itself. It's basically Wolverine.",
		"A full head of human hair can support 12 tons. Please don’t test this.",
		"There's an official Rock Paper Scissors league. Strategy matters.",
		"You can’t stand backwards on stairs. Try it. Doesn’t work.",
		"Jellyfish are biologically immortal. They just forget how to stay alive sometimes.",
		"Sometimes, when you're not looking, your socks disappear to a parallel universe.",
		"The longest hiccuping spree lasted 68 years. Legendary lung endurance.",
	];

	const factEl = document.getElementById("homepageFact");

	function getRandomFact() {
		const index = Math.floor(Math.random() * facts.length);
		return facts[index];
	}

	factEl.textContent = getRandomFact();
	factEl.addEventListener("click", () => {
		factEl.textContent = getRandomFact();
	});
});